name: test force push
on: 
  push: 
    paths:
    - "readme.md"
jobs:
  job1: 
    runs-on: ubuntu-latest
    stpes: 
     - name: Dump GitHub.event context
       env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
       run: echo "$EVENT_CONTEXT"
