name: mysql
on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-16.04
    steps:
    - name: prerelease or not
      id: pre_or_not
      run: |
        if $REF == 'refs/heads/master'
        then
          echo "::set-output name=prerelease::true"
        else
          echo "::set-output name=prerelease::true"
         fi
      env: 
        REF: ${{ github.ref }}
    - name: Create release
      run: |
        echo $prerelease
      env:
        prerelease: ${{ steps.pre_or_not.outputs.prerelease }}       
