name: mysql
on: 
  release:
     types: [created]

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT" 
  build-and-publish:
    if: " !1 == 1"
    runs-on: ubuntu-16.04
    steps:
    - name: prerelease or not
      id: pre_or_not
      run: |
        if $REF == 'refs/heads/master'
        then
          echo "::set-output name=prerelease::true"
        else
          echo "::set-output name=prerelease::false"
         fi
      env: 
        REF: ${{ github.ref }}
    - name: Create release
      run: |
        echo $prerelease
      env:
        prerelease: ${{ steps.pre_or_not.outputs.prerelease }}       
